# handlers/main.yml

- name: test nginx configuration
  command: nginx -t
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes
  when: ansible_facts['nginx_config_test'].rc == 0

